# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lumi/code/cpp/Discord++

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lumi/code/cpp/Discord++

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lumi/code/cpp/Discord++/CMakeFiles /home/lumi/code/cpp/Discord++/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lumi/code/cpp/Discord++/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Discordpp

# Build rule for target.
Discordpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Discordpp
.PHONY : Discordpp

# fast build rule for target.
Discordpp/fast:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/build
.PHONY : Discordpp/fast

example/AddStreamCommand.o: example/AddStreamCommand.cpp.o

.PHONY : example/AddStreamCommand.o

# target to build an object file
example/AddStreamCommand.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/example/AddStreamCommand.cpp.o
.PHONY : example/AddStreamCommand.cpp.o

example/AddStreamCommand.i: example/AddStreamCommand.cpp.i

.PHONY : example/AddStreamCommand.i

# target to preprocess a source file
example/AddStreamCommand.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/example/AddStreamCommand.cpp.i
.PHONY : example/AddStreamCommand.cpp.i

example/AddStreamCommand.s: example/AddStreamCommand.cpp.s

.PHONY : example/AddStreamCommand.s

# target to generate assembly for a file
example/AddStreamCommand.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/example/AddStreamCommand.cpp.s
.PHONY : example/AddStreamCommand.cpp.s

example/StreamNotifier.o: example/StreamNotifier.cpp.o

.PHONY : example/StreamNotifier.o

# target to build an object file
example/StreamNotifier.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/example/StreamNotifier.cpp.o
.PHONY : example/StreamNotifier.cpp.o

example/StreamNotifier.i: example/StreamNotifier.cpp.i

.PHONY : example/StreamNotifier.i

# target to preprocess a source file
example/StreamNotifier.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/example/StreamNotifier.cpp.i
.PHONY : example/StreamNotifier.cpp.i

example/StreamNotifier.s: example/StreamNotifier.cpp.s

.PHONY : example/StreamNotifier.s

# target to generate assembly for a file
example/StreamNotifier.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/example/StreamNotifier.cpp.s
.PHONY : example/StreamNotifier.cpp.s

example/main.o: example/main.cpp.o

.PHONY : example/main.o

# target to build an object file
example/main.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/example/main.cpp.o
.PHONY : example/main.cpp.o

example/main.i: example/main.cpp.i

.PHONY : example/main.i

# target to preprocess a source file
example/main.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/example/main.cpp.i
.PHONY : example/main.cpp.i

example/main.s: example/main.cpp.s

.PHONY : example/main.s

# target to generate assembly for a file
example/main.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/example/main.cpp.s
.PHONY : example/main.cpp.s

src/discordpp/Discordpp.o: src/discordpp/Discordpp.cpp.o

.PHONY : src/discordpp/Discordpp.o

# target to build an object file
src/discordpp/Discordpp.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/Discordpp.cpp.o
.PHONY : src/discordpp/Discordpp.cpp.o

src/discordpp/Discordpp.i: src/discordpp/Discordpp.cpp.i

.PHONY : src/discordpp/Discordpp.i

# target to preprocess a source file
src/discordpp/Discordpp.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/Discordpp.cpp.i
.PHONY : src/discordpp/Discordpp.cpp.i

src/discordpp/Discordpp.s: src/discordpp/Discordpp.cpp.s

.PHONY : src/discordpp/Discordpp.s

# target to generate assembly for a file
src/discordpp/Discordpp.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/Discordpp.cpp.s
.PHONY : src/discordpp/Discordpp.cpp.s

src/discordpp/commands/Command.o: src/discordpp/commands/Command.cpp.o

.PHONY : src/discordpp/commands/Command.o

# target to build an object file
src/discordpp/commands/Command.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/commands/Command.cpp.o
.PHONY : src/discordpp/commands/Command.cpp.o

src/discordpp/commands/Command.i: src/discordpp/commands/Command.cpp.i

.PHONY : src/discordpp/commands/Command.i

# target to preprocess a source file
src/discordpp/commands/Command.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/commands/Command.cpp.i
.PHONY : src/discordpp/commands/Command.cpp.i

src/discordpp/commands/Command.s: src/discordpp/commands/Command.cpp.s

.PHONY : src/discordpp/commands/Command.s

# target to generate assembly for a file
src/discordpp/commands/Command.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/commands/Command.cpp.s
.PHONY : src/discordpp/commands/Command.cpp.s

src/discordpp/commands/CommandManager.o: src/discordpp/commands/CommandManager.cpp.o

.PHONY : src/discordpp/commands/CommandManager.o

# target to build an object file
src/discordpp/commands/CommandManager.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/commands/CommandManager.cpp.o
.PHONY : src/discordpp/commands/CommandManager.cpp.o

src/discordpp/commands/CommandManager.i: src/discordpp/commands/CommandManager.cpp.i

.PHONY : src/discordpp/commands/CommandManager.i

# target to preprocess a source file
src/discordpp/commands/CommandManager.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/commands/CommandManager.cpp.i
.PHONY : src/discordpp/commands/CommandManager.cpp.i

src/discordpp/commands/CommandManager.s: src/discordpp/commands/CommandManager.cpp.s

.PHONY : src/discordpp/commands/CommandManager.s

# target to generate assembly for a file
src/discordpp/commands/CommandManager.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/commands/CommandManager.cpp.s
.PHONY : src/discordpp/commands/CommandManager.cpp.s

src/discordpp/commands/PingCommand.o: src/discordpp/commands/PingCommand.cpp.o

.PHONY : src/discordpp/commands/PingCommand.o

# target to build an object file
src/discordpp/commands/PingCommand.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/commands/PingCommand.cpp.o
.PHONY : src/discordpp/commands/PingCommand.cpp.o

src/discordpp/commands/PingCommand.i: src/discordpp/commands/PingCommand.cpp.i

.PHONY : src/discordpp/commands/PingCommand.i

# target to preprocess a source file
src/discordpp/commands/PingCommand.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/commands/PingCommand.cpp.i
.PHONY : src/discordpp/commands/PingCommand.cpp.i

src/discordpp/commands/PingCommand.s: src/discordpp/commands/PingCommand.cpp.s

.PHONY : src/discordpp/commands/PingCommand.s

# target to generate assembly for a file
src/discordpp/commands/PingCommand.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/commands/PingCommand.cpp.s
.PHONY : src/discordpp/commands/PingCommand.cpp.s

src/discordpp/databases/SQLiteDatabase.o: src/discordpp/databases/SQLiteDatabase.cpp.o

.PHONY : src/discordpp/databases/SQLiteDatabase.o

# target to build an object file
src/discordpp/databases/SQLiteDatabase.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/databases/SQLiteDatabase.cpp.o
.PHONY : src/discordpp/databases/SQLiteDatabase.cpp.o

src/discordpp/databases/SQLiteDatabase.i: src/discordpp/databases/SQLiteDatabase.cpp.i

.PHONY : src/discordpp/databases/SQLiteDatabase.i

# target to preprocess a source file
src/discordpp/databases/SQLiteDatabase.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/databases/SQLiteDatabase.cpp.i
.PHONY : src/discordpp/databases/SQLiteDatabase.cpp.i

src/discordpp/databases/SQLiteDatabase.s: src/discordpp/databases/SQLiteDatabase.cpp.s

.PHONY : src/discordpp/databases/SQLiteDatabase.s

# target to generate assembly for a file
src/discordpp/databases/SQLiteDatabase.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/databases/SQLiteDatabase.cpp.s
.PHONY : src/discordpp/databases/SQLiteDatabase.cpp.s

src/discordpp/events/ChannelCreateEvent.o: src/discordpp/events/ChannelCreateEvent.cpp.o

.PHONY : src/discordpp/events/ChannelCreateEvent.o

# target to build an object file
src/discordpp/events/ChannelCreateEvent.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/ChannelCreateEvent.cpp.o
.PHONY : src/discordpp/events/ChannelCreateEvent.cpp.o

src/discordpp/events/ChannelCreateEvent.i: src/discordpp/events/ChannelCreateEvent.cpp.i

.PHONY : src/discordpp/events/ChannelCreateEvent.i

# target to preprocess a source file
src/discordpp/events/ChannelCreateEvent.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/ChannelCreateEvent.cpp.i
.PHONY : src/discordpp/events/ChannelCreateEvent.cpp.i

src/discordpp/events/ChannelCreateEvent.s: src/discordpp/events/ChannelCreateEvent.cpp.s

.PHONY : src/discordpp/events/ChannelCreateEvent.s

# target to generate assembly for a file
src/discordpp/events/ChannelCreateEvent.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/ChannelCreateEvent.cpp.s
.PHONY : src/discordpp/events/ChannelCreateEvent.cpp.s

src/discordpp/events/DispatchEvent.o: src/discordpp/events/DispatchEvent.cpp.o

.PHONY : src/discordpp/events/DispatchEvent.o

# target to build an object file
src/discordpp/events/DispatchEvent.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/DispatchEvent.cpp.o
.PHONY : src/discordpp/events/DispatchEvent.cpp.o

src/discordpp/events/DispatchEvent.i: src/discordpp/events/DispatchEvent.cpp.i

.PHONY : src/discordpp/events/DispatchEvent.i

# target to preprocess a source file
src/discordpp/events/DispatchEvent.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/DispatchEvent.cpp.i
.PHONY : src/discordpp/events/DispatchEvent.cpp.i

src/discordpp/events/DispatchEvent.s: src/discordpp/events/DispatchEvent.cpp.s

.PHONY : src/discordpp/events/DispatchEvent.s

# target to generate assembly for a file
src/discordpp/events/DispatchEvent.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/DispatchEvent.cpp.s
.PHONY : src/discordpp/events/DispatchEvent.cpp.s

src/discordpp/events/Event.o: src/discordpp/events/Event.cpp.o

.PHONY : src/discordpp/events/Event.o

# target to build an object file
src/discordpp/events/Event.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/Event.cpp.o
.PHONY : src/discordpp/events/Event.cpp.o

src/discordpp/events/Event.i: src/discordpp/events/Event.cpp.i

.PHONY : src/discordpp/events/Event.i

# target to preprocess a source file
src/discordpp/events/Event.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/Event.cpp.i
.PHONY : src/discordpp/events/Event.cpp.i

src/discordpp/events/Event.s: src/discordpp/events/Event.cpp.s

.PHONY : src/discordpp/events/Event.s

# target to generate assembly for a file
src/discordpp/events/Event.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/Event.cpp.s
.PHONY : src/discordpp/events/Event.cpp.s

src/discordpp/events/GuildCreateEvent.o: src/discordpp/events/GuildCreateEvent.cpp.o

.PHONY : src/discordpp/events/GuildCreateEvent.o

# target to build an object file
src/discordpp/events/GuildCreateEvent.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/GuildCreateEvent.cpp.o
.PHONY : src/discordpp/events/GuildCreateEvent.cpp.o

src/discordpp/events/GuildCreateEvent.i: src/discordpp/events/GuildCreateEvent.cpp.i

.PHONY : src/discordpp/events/GuildCreateEvent.i

# target to preprocess a source file
src/discordpp/events/GuildCreateEvent.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/GuildCreateEvent.cpp.i
.PHONY : src/discordpp/events/GuildCreateEvent.cpp.i

src/discordpp/events/GuildCreateEvent.s: src/discordpp/events/GuildCreateEvent.cpp.s

.PHONY : src/discordpp/events/GuildCreateEvent.s

# target to generate assembly for a file
src/discordpp/events/GuildCreateEvent.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/GuildCreateEvent.cpp.s
.PHONY : src/discordpp/events/GuildCreateEvent.cpp.s

src/discordpp/events/HeartbeatACKEvent.o: src/discordpp/events/HeartbeatACKEvent.cpp.o

.PHONY : src/discordpp/events/HeartbeatACKEvent.o

# target to build an object file
src/discordpp/events/HeartbeatACKEvent.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/HeartbeatACKEvent.cpp.o
.PHONY : src/discordpp/events/HeartbeatACKEvent.cpp.o

src/discordpp/events/HeartbeatACKEvent.i: src/discordpp/events/HeartbeatACKEvent.cpp.i

.PHONY : src/discordpp/events/HeartbeatACKEvent.i

# target to preprocess a source file
src/discordpp/events/HeartbeatACKEvent.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/HeartbeatACKEvent.cpp.i
.PHONY : src/discordpp/events/HeartbeatACKEvent.cpp.i

src/discordpp/events/HeartbeatACKEvent.s: src/discordpp/events/HeartbeatACKEvent.cpp.s

.PHONY : src/discordpp/events/HeartbeatACKEvent.s

# target to generate assembly for a file
src/discordpp/events/HeartbeatACKEvent.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/HeartbeatACKEvent.cpp.s
.PHONY : src/discordpp/events/HeartbeatACKEvent.cpp.s

src/discordpp/events/HelloEvent.o: src/discordpp/events/HelloEvent.cpp.o

.PHONY : src/discordpp/events/HelloEvent.o

# target to build an object file
src/discordpp/events/HelloEvent.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/HelloEvent.cpp.o
.PHONY : src/discordpp/events/HelloEvent.cpp.o

src/discordpp/events/HelloEvent.i: src/discordpp/events/HelloEvent.cpp.i

.PHONY : src/discordpp/events/HelloEvent.i

# target to preprocess a source file
src/discordpp/events/HelloEvent.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/HelloEvent.cpp.i
.PHONY : src/discordpp/events/HelloEvent.cpp.i

src/discordpp/events/HelloEvent.s: src/discordpp/events/HelloEvent.cpp.s

.PHONY : src/discordpp/events/HelloEvent.s

# target to generate assembly for a file
src/discordpp/events/HelloEvent.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/HelloEvent.cpp.s
.PHONY : src/discordpp/events/HelloEvent.cpp.s

src/discordpp/events/MessageCreateEvent.o: src/discordpp/events/MessageCreateEvent.cpp.o

.PHONY : src/discordpp/events/MessageCreateEvent.o

# target to build an object file
src/discordpp/events/MessageCreateEvent.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/MessageCreateEvent.cpp.o
.PHONY : src/discordpp/events/MessageCreateEvent.cpp.o

src/discordpp/events/MessageCreateEvent.i: src/discordpp/events/MessageCreateEvent.cpp.i

.PHONY : src/discordpp/events/MessageCreateEvent.i

# target to preprocess a source file
src/discordpp/events/MessageCreateEvent.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/MessageCreateEvent.cpp.i
.PHONY : src/discordpp/events/MessageCreateEvent.cpp.i

src/discordpp/events/MessageCreateEvent.s: src/discordpp/events/MessageCreateEvent.cpp.s

.PHONY : src/discordpp/events/MessageCreateEvent.s

# target to generate assembly for a file
src/discordpp/events/MessageCreateEvent.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/MessageCreateEvent.cpp.s
.PHONY : src/discordpp/events/MessageCreateEvent.cpp.s

src/discordpp/events/MessageReactionAddEvent.o: src/discordpp/events/MessageReactionAddEvent.cpp.o

.PHONY : src/discordpp/events/MessageReactionAddEvent.o

# target to build an object file
src/discordpp/events/MessageReactionAddEvent.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/MessageReactionAddEvent.cpp.o
.PHONY : src/discordpp/events/MessageReactionAddEvent.cpp.o

src/discordpp/events/MessageReactionAddEvent.i: src/discordpp/events/MessageReactionAddEvent.cpp.i

.PHONY : src/discordpp/events/MessageReactionAddEvent.i

# target to preprocess a source file
src/discordpp/events/MessageReactionAddEvent.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/MessageReactionAddEvent.cpp.i
.PHONY : src/discordpp/events/MessageReactionAddEvent.cpp.i

src/discordpp/events/MessageReactionAddEvent.s: src/discordpp/events/MessageReactionAddEvent.cpp.s

.PHONY : src/discordpp/events/MessageReactionAddEvent.s

# target to generate assembly for a file
src/discordpp/events/MessageReactionAddEvent.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/MessageReactionAddEvent.cpp.s
.PHONY : src/discordpp/events/MessageReactionAddEvent.cpp.s

src/discordpp/events/PresenceUpdateEvent.o: src/discordpp/events/PresenceUpdateEvent.cpp.o

.PHONY : src/discordpp/events/PresenceUpdateEvent.o

# target to build an object file
src/discordpp/events/PresenceUpdateEvent.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/PresenceUpdateEvent.cpp.o
.PHONY : src/discordpp/events/PresenceUpdateEvent.cpp.o

src/discordpp/events/PresenceUpdateEvent.i: src/discordpp/events/PresenceUpdateEvent.cpp.i

.PHONY : src/discordpp/events/PresenceUpdateEvent.i

# target to preprocess a source file
src/discordpp/events/PresenceUpdateEvent.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/PresenceUpdateEvent.cpp.i
.PHONY : src/discordpp/events/PresenceUpdateEvent.cpp.i

src/discordpp/events/PresenceUpdateEvent.s: src/discordpp/events/PresenceUpdateEvent.cpp.s

.PHONY : src/discordpp/events/PresenceUpdateEvent.s

# target to generate assembly for a file
src/discordpp/events/PresenceUpdateEvent.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/PresenceUpdateEvent.cpp.s
.PHONY : src/discordpp/events/PresenceUpdateEvent.cpp.s

src/discordpp/events/ReadyEvent.o: src/discordpp/events/ReadyEvent.cpp.o

.PHONY : src/discordpp/events/ReadyEvent.o

# target to build an object file
src/discordpp/events/ReadyEvent.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/ReadyEvent.cpp.o
.PHONY : src/discordpp/events/ReadyEvent.cpp.o

src/discordpp/events/ReadyEvent.i: src/discordpp/events/ReadyEvent.cpp.i

.PHONY : src/discordpp/events/ReadyEvent.i

# target to preprocess a source file
src/discordpp/events/ReadyEvent.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/ReadyEvent.cpp.i
.PHONY : src/discordpp/events/ReadyEvent.cpp.i

src/discordpp/events/ReadyEvent.s: src/discordpp/events/ReadyEvent.cpp.s

.PHONY : src/discordpp/events/ReadyEvent.s

# target to generate assembly for a file
src/discordpp/events/ReadyEvent.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/ReadyEvent.cpp.s
.PHONY : src/discordpp/events/ReadyEvent.cpp.s

src/discordpp/events/TypingStartEvent.o: src/discordpp/events/TypingStartEvent.cpp.o

.PHONY : src/discordpp/events/TypingStartEvent.o

# target to build an object file
src/discordpp/events/TypingStartEvent.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/TypingStartEvent.cpp.o
.PHONY : src/discordpp/events/TypingStartEvent.cpp.o

src/discordpp/events/TypingStartEvent.i: src/discordpp/events/TypingStartEvent.cpp.i

.PHONY : src/discordpp/events/TypingStartEvent.i

# target to preprocess a source file
src/discordpp/events/TypingStartEvent.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/TypingStartEvent.cpp.i
.PHONY : src/discordpp/events/TypingStartEvent.cpp.i

src/discordpp/events/TypingStartEvent.s: src/discordpp/events/TypingStartEvent.cpp.s

.PHONY : src/discordpp/events/TypingStartEvent.s

# target to generate assembly for a file
src/discordpp/events/TypingStartEvent.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/events/TypingStartEvent.cpp.s
.PHONY : src/discordpp/events/TypingStartEvent.cpp.s

src/discordpp/guilds/Guild.o: src/discordpp/guilds/Guild.cpp.o

.PHONY : src/discordpp/guilds/Guild.o

# target to build an object file
src/discordpp/guilds/Guild.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/guilds/Guild.cpp.o
.PHONY : src/discordpp/guilds/Guild.cpp.o

src/discordpp/guilds/Guild.i: src/discordpp/guilds/Guild.cpp.i

.PHONY : src/discordpp/guilds/Guild.i

# target to preprocess a source file
src/discordpp/guilds/Guild.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/guilds/Guild.cpp.i
.PHONY : src/discordpp/guilds/Guild.cpp.i

src/discordpp/guilds/Guild.s: src/discordpp/guilds/Guild.cpp.s

.PHONY : src/discordpp/guilds/Guild.s

# target to generate assembly for a file
src/discordpp/guilds/Guild.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/guilds/Guild.cpp.s
.PHONY : src/discordpp/guilds/Guild.cpp.s

src/discordpp/guilds/GuildManager.o: src/discordpp/guilds/GuildManager.cpp.o

.PHONY : src/discordpp/guilds/GuildManager.o

# target to build an object file
src/discordpp/guilds/GuildManager.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/guilds/GuildManager.cpp.o
.PHONY : src/discordpp/guilds/GuildManager.cpp.o

src/discordpp/guilds/GuildManager.i: src/discordpp/guilds/GuildManager.cpp.i

.PHONY : src/discordpp/guilds/GuildManager.i

# target to preprocess a source file
src/discordpp/guilds/GuildManager.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/guilds/GuildManager.cpp.i
.PHONY : src/discordpp/guilds/GuildManager.cpp.i

src/discordpp/guilds/GuildManager.s: src/discordpp/guilds/GuildManager.cpp.s

.PHONY : src/discordpp/guilds/GuildManager.s

# target to generate assembly for a file
src/discordpp/guilds/GuildManager.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/guilds/GuildManager.cpp.s
.PHONY : src/discordpp/guilds/GuildManager.cpp.s

src/discordpp/money/Commands/ClaimMoneyCommand.o: src/discordpp/money/Commands/ClaimMoneyCommand.cpp.o

.PHONY : src/discordpp/money/Commands/ClaimMoneyCommand.o

# target to build an object file
src/discordpp/money/Commands/ClaimMoneyCommand.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/Commands/ClaimMoneyCommand.cpp.o
.PHONY : src/discordpp/money/Commands/ClaimMoneyCommand.cpp.o

src/discordpp/money/Commands/ClaimMoneyCommand.i: src/discordpp/money/Commands/ClaimMoneyCommand.cpp.i

.PHONY : src/discordpp/money/Commands/ClaimMoneyCommand.i

# target to preprocess a source file
src/discordpp/money/Commands/ClaimMoneyCommand.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/Commands/ClaimMoneyCommand.cpp.i
.PHONY : src/discordpp/money/Commands/ClaimMoneyCommand.cpp.i

src/discordpp/money/Commands/ClaimMoneyCommand.s: src/discordpp/money/Commands/ClaimMoneyCommand.cpp.s

.PHONY : src/discordpp/money/Commands/ClaimMoneyCommand.s

# target to generate assembly for a file
src/discordpp/money/Commands/ClaimMoneyCommand.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/Commands/ClaimMoneyCommand.cpp.s
.PHONY : src/discordpp/money/Commands/ClaimMoneyCommand.cpp.s

src/discordpp/money/Commands/DailyMoneyCommand.o: src/discordpp/money/Commands/DailyMoneyCommand.cpp.o

.PHONY : src/discordpp/money/Commands/DailyMoneyCommand.o

# target to build an object file
src/discordpp/money/Commands/DailyMoneyCommand.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/Commands/DailyMoneyCommand.cpp.o
.PHONY : src/discordpp/money/Commands/DailyMoneyCommand.cpp.o

src/discordpp/money/Commands/DailyMoneyCommand.i: src/discordpp/money/Commands/DailyMoneyCommand.cpp.i

.PHONY : src/discordpp/money/Commands/DailyMoneyCommand.i

# target to preprocess a source file
src/discordpp/money/Commands/DailyMoneyCommand.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/Commands/DailyMoneyCommand.cpp.i
.PHONY : src/discordpp/money/Commands/DailyMoneyCommand.cpp.i

src/discordpp/money/Commands/DailyMoneyCommand.s: src/discordpp/money/Commands/DailyMoneyCommand.cpp.s

.PHONY : src/discordpp/money/Commands/DailyMoneyCommand.s

# target to generate assembly for a file
src/discordpp/money/Commands/DailyMoneyCommand.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/Commands/DailyMoneyCommand.cpp.s
.PHONY : src/discordpp/money/Commands/DailyMoneyCommand.cpp.s

src/discordpp/money/Commands/LeaderboardCommand.o: src/discordpp/money/Commands/LeaderboardCommand.cpp.o

.PHONY : src/discordpp/money/Commands/LeaderboardCommand.o

# target to build an object file
src/discordpp/money/Commands/LeaderboardCommand.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/Commands/LeaderboardCommand.cpp.o
.PHONY : src/discordpp/money/Commands/LeaderboardCommand.cpp.o

src/discordpp/money/Commands/LeaderboardCommand.i: src/discordpp/money/Commands/LeaderboardCommand.cpp.i

.PHONY : src/discordpp/money/Commands/LeaderboardCommand.i

# target to preprocess a source file
src/discordpp/money/Commands/LeaderboardCommand.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/Commands/LeaderboardCommand.cpp.i
.PHONY : src/discordpp/money/Commands/LeaderboardCommand.cpp.i

src/discordpp/money/Commands/LeaderboardCommand.s: src/discordpp/money/Commands/LeaderboardCommand.cpp.s

.PHONY : src/discordpp/money/Commands/LeaderboardCommand.s

# target to generate assembly for a file
src/discordpp/money/Commands/LeaderboardCommand.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/Commands/LeaderboardCommand.cpp.s
.PHONY : src/discordpp/money/Commands/LeaderboardCommand.cpp.s

src/discordpp/money/Money.o: src/discordpp/money/Money.cpp.o

.PHONY : src/discordpp/money/Money.o

# target to build an object file
src/discordpp/money/Money.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/Money.cpp.o
.PHONY : src/discordpp/money/Money.cpp.o

src/discordpp/money/Money.i: src/discordpp/money/Money.cpp.i

.PHONY : src/discordpp/money/Money.i

# target to preprocess a source file
src/discordpp/money/Money.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/Money.cpp.i
.PHONY : src/discordpp/money/Money.cpp.i

src/discordpp/money/Money.s: src/discordpp/money/Money.cpp.s

.PHONY : src/discordpp/money/Money.s

# target to generate assembly for a file
src/discordpp/money/Money.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/Money.cpp.s
.PHONY : src/discordpp/money/Money.cpp.s

src/discordpp/money/MoneyManager.o: src/discordpp/money/MoneyManager.cpp.o

.PHONY : src/discordpp/money/MoneyManager.o

# target to build an object file
src/discordpp/money/MoneyManager.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/MoneyManager.cpp.o
.PHONY : src/discordpp/money/MoneyManager.cpp.o

src/discordpp/money/MoneyManager.i: src/discordpp/money/MoneyManager.cpp.i

.PHONY : src/discordpp/money/MoneyManager.i

# target to preprocess a source file
src/discordpp/money/MoneyManager.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/MoneyManager.cpp.i
.PHONY : src/discordpp/money/MoneyManager.cpp.i

src/discordpp/money/MoneyManager.s: src/discordpp/money/MoneyManager.cpp.s

.PHONY : src/discordpp/money/MoneyManager.s

# target to generate assembly for a file
src/discordpp/money/MoneyManager.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/money/MoneyManager.cpp.s
.PHONY : src/discordpp/money/MoneyManager.cpp.s

src/discordpp/objects/Channel.o: src/discordpp/objects/Channel.cpp.o

.PHONY : src/discordpp/objects/Channel.o

# target to build an object file
src/discordpp/objects/Channel.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Channel.cpp.o
.PHONY : src/discordpp/objects/Channel.cpp.o

src/discordpp/objects/Channel.i: src/discordpp/objects/Channel.cpp.i

.PHONY : src/discordpp/objects/Channel.i

# target to preprocess a source file
src/discordpp/objects/Channel.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Channel.cpp.i
.PHONY : src/discordpp/objects/Channel.cpp.i

src/discordpp/objects/Channel.s: src/discordpp/objects/Channel.cpp.s

.PHONY : src/discordpp/objects/Channel.s

# target to generate assembly for a file
src/discordpp/objects/Channel.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Channel.cpp.s
.PHONY : src/discordpp/objects/Channel.cpp.s

src/discordpp/objects/Emoji.o: src/discordpp/objects/Emoji.cpp.o

.PHONY : src/discordpp/objects/Emoji.o

# target to build an object file
src/discordpp/objects/Emoji.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Emoji.cpp.o
.PHONY : src/discordpp/objects/Emoji.cpp.o

src/discordpp/objects/Emoji.i: src/discordpp/objects/Emoji.cpp.i

.PHONY : src/discordpp/objects/Emoji.i

# target to preprocess a source file
src/discordpp/objects/Emoji.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Emoji.cpp.i
.PHONY : src/discordpp/objects/Emoji.cpp.i

src/discordpp/objects/Emoji.s: src/discordpp/objects/Emoji.cpp.s

.PHONY : src/discordpp/objects/Emoji.s

# target to generate assembly for a file
src/discordpp/objects/Emoji.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Emoji.cpp.s
.PHONY : src/discordpp/objects/Emoji.cpp.s

src/discordpp/objects/Message.o: src/discordpp/objects/Message.cpp.o

.PHONY : src/discordpp/objects/Message.o

# target to build an object file
src/discordpp/objects/Message.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Message.cpp.o
.PHONY : src/discordpp/objects/Message.cpp.o

src/discordpp/objects/Message.i: src/discordpp/objects/Message.cpp.i

.PHONY : src/discordpp/objects/Message.i

# target to preprocess a source file
src/discordpp/objects/Message.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Message.cpp.i
.PHONY : src/discordpp/objects/Message.cpp.i

src/discordpp/objects/Message.s: src/discordpp/objects/Message.cpp.s

.PHONY : src/discordpp/objects/Message.s

# target to generate assembly for a file
src/discordpp/objects/Message.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Message.cpp.s
.PHONY : src/discordpp/objects/Message.cpp.s

src/discordpp/objects/Role.o: src/discordpp/objects/Role.cpp.o

.PHONY : src/discordpp/objects/Role.o

# target to build an object file
src/discordpp/objects/Role.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Role.cpp.o
.PHONY : src/discordpp/objects/Role.cpp.o

src/discordpp/objects/Role.i: src/discordpp/objects/Role.cpp.i

.PHONY : src/discordpp/objects/Role.i

# target to preprocess a source file
src/discordpp/objects/Role.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Role.cpp.i
.PHONY : src/discordpp/objects/Role.cpp.i

src/discordpp/objects/Role.s: src/discordpp/objects/Role.cpp.s

.PHONY : src/discordpp/objects/Role.s

# target to generate assembly for a file
src/discordpp/objects/Role.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Role.cpp.s
.PHONY : src/discordpp/objects/Role.cpp.s

src/discordpp/objects/Snowflake.o: src/discordpp/objects/Snowflake.cpp.o

.PHONY : src/discordpp/objects/Snowflake.o

# target to build an object file
src/discordpp/objects/Snowflake.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Snowflake.cpp.o
.PHONY : src/discordpp/objects/Snowflake.cpp.o

src/discordpp/objects/Snowflake.i: src/discordpp/objects/Snowflake.cpp.i

.PHONY : src/discordpp/objects/Snowflake.i

# target to preprocess a source file
src/discordpp/objects/Snowflake.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Snowflake.cpp.i
.PHONY : src/discordpp/objects/Snowflake.cpp.i

src/discordpp/objects/Snowflake.s: src/discordpp/objects/Snowflake.cpp.s

.PHONY : src/discordpp/objects/Snowflake.s

# target to generate assembly for a file
src/discordpp/objects/Snowflake.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/objects/Snowflake.cpp.s
.PHONY : src/discordpp/objects/Snowflake.cpp.s

src/discordpp/rest/DiscordAPI.o: src/discordpp/rest/DiscordAPI.cpp.o

.PHONY : src/discordpp/rest/DiscordAPI.o

# target to build an object file
src/discordpp/rest/DiscordAPI.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/rest/DiscordAPI.cpp.o
.PHONY : src/discordpp/rest/DiscordAPI.cpp.o

src/discordpp/rest/DiscordAPI.i: src/discordpp/rest/DiscordAPI.cpp.i

.PHONY : src/discordpp/rest/DiscordAPI.i

# target to preprocess a source file
src/discordpp/rest/DiscordAPI.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/rest/DiscordAPI.cpp.i
.PHONY : src/discordpp/rest/DiscordAPI.cpp.i

src/discordpp/rest/DiscordAPI.s: src/discordpp/rest/DiscordAPI.cpp.s

.PHONY : src/discordpp/rest/DiscordAPI.s

# target to generate assembly for a file
src/discordpp/rest/DiscordAPI.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/rest/DiscordAPI.cpp.s
.PHONY : src/discordpp/rest/DiscordAPI.cpp.s

src/discordpp/rest/PicartoAPI.o: src/discordpp/rest/PicartoAPI.cpp.o

.PHONY : src/discordpp/rest/PicartoAPI.o

# target to build an object file
src/discordpp/rest/PicartoAPI.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/rest/PicartoAPI.cpp.o
.PHONY : src/discordpp/rest/PicartoAPI.cpp.o

src/discordpp/rest/PicartoAPI.i: src/discordpp/rest/PicartoAPI.cpp.i

.PHONY : src/discordpp/rest/PicartoAPI.i

# target to preprocess a source file
src/discordpp/rest/PicartoAPI.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/rest/PicartoAPI.cpp.i
.PHONY : src/discordpp/rest/PicartoAPI.cpp.i

src/discordpp/rest/PicartoAPI.s: src/discordpp/rest/PicartoAPI.cpp.s

.PHONY : src/discordpp/rest/PicartoAPI.s

# target to generate assembly for a file
src/discordpp/rest/PicartoAPI.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/rest/PicartoAPI.cpp.s
.PHONY : src/discordpp/rest/PicartoAPI.cpp.s

src/discordpp/rest/RestAPI.o: src/discordpp/rest/RestAPI.cpp.o

.PHONY : src/discordpp/rest/RestAPI.o

# target to build an object file
src/discordpp/rest/RestAPI.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/rest/RestAPI.cpp.o
.PHONY : src/discordpp/rest/RestAPI.cpp.o

src/discordpp/rest/RestAPI.i: src/discordpp/rest/RestAPI.cpp.i

.PHONY : src/discordpp/rest/RestAPI.i

# target to preprocess a source file
src/discordpp/rest/RestAPI.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/rest/RestAPI.cpp.i
.PHONY : src/discordpp/rest/RestAPI.cpp.i

src/discordpp/rest/RestAPI.s: src/discordpp/rest/RestAPI.cpp.s

.PHONY : src/discordpp/rest/RestAPI.s

# target to generate assembly for a file
src/discordpp/rest/RestAPI.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/rest/RestAPI.cpp.s
.PHONY : src/discordpp/rest/RestAPI.cpp.s

src/discordpp/rest/TwitchAPI.o: src/discordpp/rest/TwitchAPI.cpp.o

.PHONY : src/discordpp/rest/TwitchAPI.o

# target to build an object file
src/discordpp/rest/TwitchAPI.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/rest/TwitchAPI.cpp.o
.PHONY : src/discordpp/rest/TwitchAPI.cpp.o

src/discordpp/rest/TwitchAPI.i: src/discordpp/rest/TwitchAPI.cpp.i

.PHONY : src/discordpp/rest/TwitchAPI.i

# target to preprocess a source file
src/discordpp/rest/TwitchAPI.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/rest/TwitchAPI.cpp.i
.PHONY : src/discordpp/rest/TwitchAPI.cpp.i

src/discordpp/rest/TwitchAPI.s: src/discordpp/rest/TwitchAPI.cpp.s

.PHONY : src/discordpp/rest/TwitchAPI.s

# target to generate assembly for a file
src/discordpp/rest/TwitchAPI.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/rest/TwitchAPI.cpp.s
.PHONY : src/discordpp/rest/TwitchAPI.cpp.s

src/discordpp/tasks/HeartbeatTask.o: src/discordpp/tasks/HeartbeatTask.cpp.o

.PHONY : src/discordpp/tasks/HeartbeatTask.o

# target to build an object file
src/discordpp/tasks/HeartbeatTask.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/tasks/HeartbeatTask.cpp.o
.PHONY : src/discordpp/tasks/HeartbeatTask.cpp.o

src/discordpp/tasks/HeartbeatTask.i: src/discordpp/tasks/HeartbeatTask.cpp.i

.PHONY : src/discordpp/tasks/HeartbeatTask.i

# target to preprocess a source file
src/discordpp/tasks/HeartbeatTask.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/tasks/HeartbeatTask.cpp.i
.PHONY : src/discordpp/tasks/HeartbeatTask.cpp.i

src/discordpp/tasks/HeartbeatTask.s: src/discordpp/tasks/HeartbeatTask.cpp.s

.PHONY : src/discordpp/tasks/HeartbeatTask.s

# target to generate assembly for a file
src/discordpp/tasks/HeartbeatTask.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/tasks/HeartbeatTask.cpp.s
.PHONY : src/discordpp/tasks/HeartbeatTask.cpp.s

src/discordpp/tasks/Task.o: src/discordpp/tasks/Task.cpp.o

.PHONY : src/discordpp/tasks/Task.o

# target to build an object file
src/discordpp/tasks/Task.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/tasks/Task.cpp.o
.PHONY : src/discordpp/tasks/Task.cpp.o

src/discordpp/tasks/Task.i: src/discordpp/tasks/Task.cpp.i

.PHONY : src/discordpp/tasks/Task.i

# target to preprocess a source file
src/discordpp/tasks/Task.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/tasks/Task.cpp.i
.PHONY : src/discordpp/tasks/Task.cpp.i

src/discordpp/tasks/Task.s: src/discordpp/tasks/Task.cpp.s

.PHONY : src/discordpp/tasks/Task.s

# target to generate assembly for a file
src/discordpp/tasks/Task.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/tasks/Task.cpp.s
.PHONY : src/discordpp/tasks/Task.cpp.s

src/discordpp/users/User.o: src/discordpp/users/User.cpp.o

.PHONY : src/discordpp/users/User.o

# target to build an object file
src/discordpp/users/User.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/users/User.cpp.o
.PHONY : src/discordpp/users/User.cpp.o

src/discordpp/users/User.i: src/discordpp/users/User.cpp.i

.PHONY : src/discordpp/users/User.i

# target to preprocess a source file
src/discordpp/users/User.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/users/User.cpp.i
.PHONY : src/discordpp/users/User.cpp.i

src/discordpp/users/User.s: src/discordpp/users/User.cpp.s

.PHONY : src/discordpp/users/User.s

# target to generate assembly for a file
src/discordpp/users/User.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/users/User.cpp.s
.PHONY : src/discordpp/users/User.cpp.s

src/discordpp/users/UserManager.o: src/discordpp/users/UserManager.cpp.o

.PHONY : src/discordpp/users/UserManager.o

# target to build an object file
src/discordpp/users/UserManager.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/users/UserManager.cpp.o
.PHONY : src/discordpp/users/UserManager.cpp.o

src/discordpp/users/UserManager.i: src/discordpp/users/UserManager.cpp.i

.PHONY : src/discordpp/users/UserManager.i

# target to preprocess a source file
src/discordpp/users/UserManager.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/users/UserManager.cpp.i
.PHONY : src/discordpp/users/UserManager.cpp.i

src/discordpp/users/UserManager.s: src/discordpp/users/UserManager.cpp.s

.PHONY : src/discordpp/users/UserManager.s

# target to generate assembly for a file
src/discordpp/users/UserManager.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/users/UserManager.cpp.s
.PHONY : src/discordpp/users/UserManager.cpp.s

src/discordpp/websocket/Gateway.o: src/discordpp/websocket/Gateway.cpp.o

.PHONY : src/discordpp/websocket/Gateway.o

# target to build an object file
src/discordpp/websocket/Gateway.cpp.o:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/websocket/Gateway.cpp.o
.PHONY : src/discordpp/websocket/Gateway.cpp.o

src/discordpp/websocket/Gateway.i: src/discordpp/websocket/Gateway.cpp.i

.PHONY : src/discordpp/websocket/Gateway.i

# target to preprocess a source file
src/discordpp/websocket/Gateway.cpp.i:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/websocket/Gateway.cpp.i
.PHONY : src/discordpp/websocket/Gateway.cpp.i

src/discordpp/websocket/Gateway.s: src/discordpp/websocket/Gateway.cpp.s

.PHONY : src/discordpp/websocket/Gateway.s

# target to generate assembly for a file
src/discordpp/websocket/Gateway.cpp.s:
	$(MAKE) -f CMakeFiles/Discordpp.dir/build.make CMakeFiles/Discordpp.dir/src/discordpp/websocket/Gateway.cpp.s
.PHONY : src/discordpp/websocket/Gateway.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Discordpp"
	@echo "... edit_cache"
	@echo "... example/AddStreamCommand.o"
	@echo "... example/AddStreamCommand.i"
	@echo "... example/AddStreamCommand.s"
	@echo "... example/StreamNotifier.o"
	@echo "... example/StreamNotifier.i"
	@echo "... example/StreamNotifier.s"
	@echo "... example/main.o"
	@echo "... example/main.i"
	@echo "... example/main.s"
	@echo "... src/discordpp/Discordpp.o"
	@echo "... src/discordpp/Discordpp.i"
	@echo "... src/discordpp/Discordpp.s"
	@echo "... src/discordpp/commands/Command.o"
	@echo "... src/discordpp/commands/Command.i"
	@echo "... src/discordpp/commands/Command.s"
	@echo "... src/discordpp/commands/CommandManager.o"
	@echo "... src/discordpp/commands/CommandManager.i"
	@echo "... src/discordpp/commands/CommandManager.s"
	@echo "... src/discordpp/commands/PingCommand.o"
	@echo "... src/discordpp/commands/PingCommand.i"
	@echo "... src/discordpp/commands/PingCommand.s"
	@echo "... src/discordpp/databases/SQLiteDatabase.o"
	@echo "... src/discordpp/databases/SQLiteDatabase.i"
	@echo "... src/discordpp/databases/SQLiteDatabase.s"
	@echo "... src/discordpp/events/ChannelCreateEvent.o"
	@echo "... src/discordpp/events/ChannelCreateEvent.i"
	@echo "... src/discordpp/events/ChannelCreateEvent.s"
	@echo "... src/discordpp/events/DispatchEvent.o"
	@echo "... src/discordpp/events/DispatchEvent.i"
	@echo "... src/discordpp/events/DispatchEvent.s"
	@echo "... src/discordpp/events/Event.o"
	@echo "... src/discordpp/events/Event.i"
	@echo "... src/discordpp/events/Event.s"
	@echo "... src/discordpp/events/GuildCreateEvent.o"
	@echo "... src/discordpp/events/GuildCreateEvent.i"
	@echo "... src/discordpp/events/GuildCreateEvent.s"
	@echo "... src/discordpp/events/HeartbeatACKEvent.o"
	@echo "... src/discordpp/events/HeartbeatACKEvent.i"
	@echo "... src/discordpp/events/HeartbeatACKEvent.s"
	@echo "... src/discordpp/events/HelloEvent.o"
	@echo "... src/discordpp/events/HelloEvent.i"
	@echo "... src/discordpp/events/HelloEvent.s"
	@echo "... src/discordpp/events/MessageCreateEvent.o"
	@echo "... src/discordpp/events/MessageCreateEvent.i"
	@echo "... src/discordpp/events/MessageCreateEvent.s"
	@echo "... src/discordpp/events/MessageReactionAddEvent.o"
	@echo "... src/discordpp/events/MessageReactionAddEvent.i"
	@echo "... src/discordpp/events/MessageReactionAddEvent.s"
	@echo "... src/discordpp/events/PresenceUpdateEvent.o"
	@echo "... src/discordpp/events/PresenceUpdateEvent.i"
	@echo "... src/discordpp/events/PresenceUpdateEvent.s"
	@echo "... src/discordpp/events/ReadyEvent.o"
	@echo "... src/discordpp/events/ReadyEvent.i"
	@echo "... src/discordpp/events/ReadyEvent.s"
	@echo "... src/discordpp/events/TypingStartEvent.o"
	@echo "... src/discordpp/events/TypingStartEvent.i"
	@echo "... src/discordpp/events/TypingStartEvent.s"
	@echo "... src/discordpp/guilds/Guild.o"
	@echo "... src/discordpp/guilds/Guild.i"
	@echo "... src/discordpp/guilds/Guild.s"
	@echo "... src/discordpp/guilds/GuildManager.o"
	@echo "... src/discordpp/guilds/GuildManager.i"
	@echo "... src/discordpp/guilds/GuildManager.s"
	@echo "... src/discordpp/money/Commands/ClaimMoneyCommand.o"
	@echo "... src/discordpp/money/Commands/ClaimMoneyCommand.i"
	@echo "... src/discordpp/money/Commands/ClaimMoneyCommand.s"
	@echo "... src/discordpp/money/Commands/DailyMoneyCommand.o"
	@echo "... src/discordpp/money/Commands/DailyMoneyCommand.i"
	@echo "... src/discordpp/money/Commands/DailyMoneyCommand.s"
	@echo "... src/discordpp/money/Commands/LeaderboardCommand.o"
	@echo "... src/discordpp/money/Commands/LeaderboardCommand.i"
	@echo "... src/discordpp/money/Commands/LeaderboardCommand.s"
	@echo "... src/discordpp/money/Money.o"
	@echo "... src/discordpp/money/Money.i"
	@echo "... src/discordpp/money/Money.s"
	@echo "... src/discordpp/money/MoneyManager.o"
	@echo "... src/discordpp/money/MoneyManager.i"
	@echo "... src/discordpp/money/MoneyManager.s"
	@echo "... src/discordpp/objects/Channel.o"
	@echo "... src/discordpp/objects/Channel.i"
	@echo "... src/discordpp/objects/Channel.s"
	@echo "... src/discordpp/objects/Emoji.o"
	@echo "... src/discordpp/objects/Emoji.i"
	@echo "... src/discordpp/objects/Emoji.s"
	@echo "... src/discordpp/objects/Message.o"
	@echo "... src/discordpp/objects/Message.i"
	@echo "... src/discordpp/objects/Message.s"
	@echo "... src/discordpp/objects/Role.o"
	@echo "... src/discordpp/objects/Role.i"
	@echo "... src/discordpp/objects/Role.s"
	@echo "... src/discordpp/objects/Snowflake.o"
	@echo "... src/discordpp/objects/Snowflake.i"
	@echo "... src/discordpp/objects/Snowflake.s"
	@echo "... src/discordpp/rest/DiscordAPI.o"
	@echo "... src/discordpp/rest/DiscordAPI.i"
	@echo "... src/discordpp/rest/DiscordAPI.s"
	@echo "... src/discordpp/rest/PicartoAPI.o"
	@echo "... src/discordpp/rest/PicartoAPI.i"
	@echo "... src/discordpp/rest/PicartoAPI.s"
	@echo "... src/discordpp/rest/RestAPI.o"
	@echo "... src/discordpp/rest/RestAPI.i"
	@echo "... src/discordpp/rest/RestAPI.s"
	@echo "... src/discordpp/rest/TwitchAPI.o"
	@echo "... src/discordpp/rest/TwitchAPI.i"
	@echo "... src/discordpp/rest/TwitchAPI.s"
	@echo "... src/discordpp/tasks/HeartbeatTask.o"
	@echo "... src/discordpp/tasks/HeartbeatTask.i"
	@echo "... src/discordpp/tasks/HeartbeatTask.s"
	@echo "... src/discordpp/tasks/Task.o"
	@echo "... src/discordpp/tasks/Task.i"
	@echo "... src/discordpp/tasks/Task.s"
	@echo "... src/discordpp/users/User.o"
	@echo "... src/discordpp/users/User.i"
	@echo "... src/discordpp/users/User.s"
	@echo "... src/discordpp/users/UserManager.o"
	@echo "... src/discordpp/users/UserManager.i"
	@echo "... src/discordpp/users/UserManager.s"
	@echo "... src/discordpp/websocket/Gateway.o"
	@echo "... src/discordpp/websocket/Gateway.i"
	@echo "... src/discordpp/websocket/Gateway.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

